fixes

diff --git a/src/lib/azure/az_lib b/src/lib/azure/az_lib
--- a/src/lib/azure/az_lib
+++ b/src/lib/azure/az_lib
@@ -1,5 +1,7 @@
 #! /bin/bash
 
+set -e
+
 # Function to login to Azure
 az_login() {
     # Check if the required environment variables are set
@@ -52,12 +54,14 @@ install_azure_cli() {
 # Check and install Azure CLI
 check_az_cli() {
     logger "INFO" "Checking if Azure CLI is installed..."
-    if [ ! command -v az &> /dev/null ]; then
+    if ! command -v az &> /dev/null; then
         install_azure_cli
     fi
+
     az version
+
     if [ $? -ne 0 ]; then
-    logger "ERROR" "Failed to check Azure CLI version"
+        logger "ERROR" "Failed to check Azure CLI version"
         exit 1
     fi
     logger "INFO" "Azure CLI is installed."
diff --git a/src/lib/initialize b/src/lib/initialize
--- a/src/lib/initialize
+++ b/src/lib/initialize
@@ -1,14 +1,27 @@
 #! /bin/bash
 
 set -e
+source src/lib/helper
+
+# APP_ENVIRONMENT should be passed either from environment variable or pipeline parameter
+if [ -z $APP_ENVIRONMENT] && [ -z $ENV ]; then 
+    logger "ERROR" "APP_ENVIRONMENT or ENV must be defined"
+    exit 1
+fi
+
 if [ -z $ENV ]; then ENV=$APP_ENVIRONMENT; fi
 
-SECRETS_FILE="config/environments/${ENV}/secrets.enc.yaml"
+ENV_CONFIG_PATH="config/environments/${ENV}"
+SECRETS_FILE="${ENV_CONFIG_PATH}/secrets.enc.yaml"
 
-PROPERTIES_FILE="config/environments/${ENV}/${ENV}.properties"
+ENV_PROPERTIES="${ENV_CONFIG_PATH}/${ENV}.properties"
+UI_PROPERTIES="${ENV_CONFIG_PATH}/${ENV}.ui.properties"
+WEBSERVICE_PROPERTIES="${ENV_CONFIG_PATH}/${ENV}.webservice.properties"
 
-source ${PROPERTIES_FILE}
-source src/lib/helper
+source ${ENV_PROPERTIES}
+source ${UI_PROPERTIES}
+source ${WEBSERVICE_PROPERTIES}
+
 source src/lib/azure/az_lib
 
 check_az_cli
@@ -18,4 +31,13 @@ az_login
 
 logger "INFO" "Reading secrets from local encrypted file"
 fetch_secrets $SECRETS_FILE
+
+logger "INFO" "Downloading Build Artificats to local path: $LOCAL_ARTIFACT_DIR"
+download_artifact
+
+logger "INFO" "Replacing placeholders in app properties file with values from secrets file"
+replace_secrets
+
+logger "INFO" "Replacing placeholders in app properties file with values from properties file"
+replace_properties
 
